### ISSUE TITLE
issue with Document ready in jQuery 3.4.1

### ISSUE THREAD

**Issue by michaelz649** [nickpotafiy/jstars#1]
With jQuery 3.4.1 don't work document ready, line 74-76.

```
$(document.body).ready(function () {
     $('.jstars').jstars();
});
```

Changing with "window load"  work perfectly:

```
$("window").on("load", function () {
     $('.jstars').jstars();
});
```

$(document).ready deprecated in jQuery3
https://jquery.com/upgrade-guide/3.0/#deprecated-document-ready-handlers-other-than-jquery-function

**Comment by nickpotafiy** [comment]
Implemented jQuery's suggested `$(fn)` ready handler.

https://github.com/nickpotafiy/jstars/commit/ff30d12f9d4f42a8c63d2929fbabb064dd861c68
